# Generated by Django 3.0.6 on 2020-05-29 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField(default=0)),
                ('data_nascimento', models.DateField(null=True)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('ND', 'Não definido'), ('M', 'Masculino'), ('F', 'Feminino')], default='ND', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.CharField(choices=[('N', 'Não cursado'), ('I', 'Incompleto'), ('C', 'Completo')], default='N', max_length=1)),
                ('nivel', models.CharField(choices=[('F', 'Ensino Fundamental'), ('M', 'Ensino Médio'), ('G', 'Graduação'), ('P', 'Pós-graduação')], default='F', max_length=1)),
                ('instituicao', models.CharField(max_length=200)),
                ('anoFinal', models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1900)])),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('municipio', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='MG', max_length=2)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Pessoa')),
            ],
        ),
    ]
