# Generated by Django 3.0.6 on 2020-05-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temEmprego', models.BooleanField(default=False)),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Pessoa')),
            ],
        ),
    ]
