# Generated by Django 3.0.6 on 2020-05-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='cargo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='empresa',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
