# Generated by Django 3.0.6 on 2020-05-30 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20200530_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolaridade',
            name='anoFinal',
            field=models.IntegerField(default=2020, null=True, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
    ]
